apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhdh-k8s-plugin
  namespace: {{ _ocp4_workload_mad_roadshow_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhdh-k8s-plugin
subjects:
- kind: ServiceAccount
  name: rhdh-k8s-plugin
  namespace: devhub
