{{- if .Values.useCatalogSnapshot -}}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .Values.catalogSource.name }}
  namespace: {{ .Values.catalogSource.namespace }}
spec:
  sourceType: grpc
  image: "{{ .Values.catalogSource.image }}:{{ .Values.catalogSource.tag }}"
  displayName: "{{ .Values.catalogSource.name }}"
  publisher: "Red Hat AgnosticD"
{{- end -}}
