kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-tekton-rbc
subjects:
  - kind: ServiceAccount
    name: argocd-devhub-argocd-application-controller
    namespace: {{ $.Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-tekton