kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-tekton
rules:
  - verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
    apiGroups:
      - tekton.dev
    resources:
      - '*'
