apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-plugins
data:
  includes:
        - dynamic-plugins.default.yaml
      plugins:
        - disabled: false
          package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic
        - disabled: false
          package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab
        - disabled: false
          package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-dynamic
        - disabled: false
          package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-gitlab-dynamic
        - disabled: false
          package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        - disabled: false
          package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        - disabled: false
          package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-topology
        - disabled: false
          package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
        - disabled: false
          package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-argocd-dynamic
        - disabled: false
          package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd
        - disabled: false
          package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-ocm
        - disabled: false
          package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-ocm-backend-dynamic
        - disabled: false
          package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-module-utils-dynamic
        - disabled: false
          package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-keycloak-backend-dynamic
        - disabled: false
          package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-tekton
          pluginConfig:
            dynamicPlugins:
              frontend:
                janus-idp.backstage-plugin-tekton:
                  mountPoints:
                  - config:
                      if:
                        allOf:
                        - isTektonCIAvailable
                      layout:
                        gridColumn: 1 / -1
                        gridRowStart: 1
                    importName: TektonCI
                    mountPoint: entity.page.ci/cards
