kind: Secret
apiVersion: v1
metadata:
  name: rhdh-keycloak-creds
stringData:
  rhsso.clientId: {{ $.Values.oauth2Proxy.clientId }}
  rhsso.clientSecret: {{ $.Values.oauth2Proxy.clientSecret }}
type: Opaque