kind: Secret
apiVersion: v1
metadata:
  name: rhdh-keycloak-creds
stringData:
  oauth2Proxy.cookieSecret: {{ $.Values.oauth2Proxy.cookieSecret }}
  oauth2Proxy.clientId: {{ $.Values.oauth2Proxy.clientId }}
  oauth2Proxy.clientSecret: {{ $.Values.oauth2Proxy.clientSecret }}
  oauth2Proxy.issuerUrl: {{ $.Values.oauth2Proxy.issuerUrl }}
  oauth2Proxy.baseUrl: {{ $.Values.oauth2Proxy.baseUrl }}
  oauth2Proxy.realm: {{ $.Values.oauth2Proxy.realm }}
  rhdh.backend.baseUrl: {{ $.Values.rhdh.backend.baseUrl }}
type: Opaque